export const GET_CHAT_ROOM_LIST = 'GET_CHAT_ROOM_LIST';
export const GET_CHAT_ROOM_LIST_SUCCESS = 'GET_CHAT_ROOM_LIST_SUCCESS';
export const GET_CHAT_ROOM_LIST_FAILED = 'GET_CHAT_ROOM_LIST_FAILED';

export const GET_ONE_CHAT_ROOM = 'GET_ONE_CHAT_ROOM';
export const GET_ONE_CHAT_ROOM_SUCCESS = 'GET_ONE_CHAT_ROOM_SUCCESS';
export const GET_ONE_CHAT_ROOM_FAILED = 'GET_ONE_CHAT_ROOM_FAILED';

export const POST_MESSAGE_CHAT = 'POST_MESSAGE_CHAT';
export const POST_MESSAGE_CHAT_SUCCESS = 'POST_MESSAGE_CHAT_SUCCESS';
export const POST_MESSAGE_CHAT_FAILED = 'POST_MESSAGE_CHAT_FAILED';

export const MARK_MESSAGE_READ_CHAT = 'MARK_MESSAGE_READ_CHAT';
export const MARK_MESSAGE_READ_CHAT_SUCCESS = 'MARK_MESSAGE_READ_CHAT_SUCCESS';
export const MARK_MESSAGE_READ_CHAT_FAILED = 'MARK_MESSAGE_READ_CHAT_FAILED';
