export const GET_COURS_LIST = 'GET_COURS_LIST';
export const GET_COURS_LIST_SUCCESS = 'GET_COURS_LIST_SUCCESS';
export const GET_COURS_LIST_FAILED = 'GET_COURS_LIST_FAILED';

export const GET_ONE_COURS = 'GET_ONE_COURS';
export const GET_ONE_COURS_SUCCESS = 'GET_ONE_COURS_SUCCESS';
export const GET_ONE_COURS_FAILED = 'GET_ONE_COURS_FAILED';

export const GET_LIST_QUESTIONS_COURS = 'GET_LIST_QUESTIONS_COURS';
export const GET_LIST_QUESTIONS_COURS_SUCCESS =
  'GET_LIST_QUESTIONS_COURS_SUCCESS';
export const GET_LIST_QUESTIONS_COURS_FAILED =
  'GET_LIST_QUESTIONS_COURS_FAILED';

export const GET_CHAPTERS_COURS = 'GET_CHAPTERS_COURS';
export const GET_CHAPTERS_COURS_SUCCESS = 'GET_CHAPTERS_COURS_SUCCESS';
export const GET_CHAPTERS_COURS_FAILED = 'GET_CHAPTERS_COURS_FAILED';

export const GET_SESSIONS_COURS = 'GET_SESSIONS_COURS';
export const GET_SESSIONS_COURS_SUCCESS = 'GET_SESSIONS_COURS_SUCCESS';
export const GET_SESSIONS_COURS_FAILED = 'GET_SESSIONS_COURS_FAILED';
