export const GET_EVENTS_LIST = 'GET_EVENTS_LIST';
export const GET_EVENTS_LIST_SUCCESS = 'GET_EVENTS_LIST_SUCCESS';
export const GET_EVENTS_LIST_FAILED = 'GET_EVENTS_LIST_FAILED';

export const SUBSCRIBE_EVENT = 'SUBSCRIBE_EVENT';
export const SUBSCRIBE_EVENT_SUCCESS = 'SUBSCRIBE_EVENT_SUCCESS';
export const SUBSCRIBE_EVENT_FAILED = 'SUBSCRIBE_EVENT_FAILED';