export const GET_MY_INSTITUTIONS = 'GET_MY_INSTITUTIONS';
export const GET_MY_INSTITUTIONS_SUCCESS = 'GET_MY_INSTITUTIONS_SUCCESS';
export const GET_MY_INSTITUTIONS_FAILED = 'GET_MY_INSTITUTIONS_FAILED';

export const GET_ONE_INSTITUTION = 'GET_ONE_INSTITUTION';
export const GET_ONE_INSTITUTION_SUCCESS = 'GET_ONE_INSTITUTION_SUCCESS';
export const GET_ONE_INSTITUTION_FAILED = 'GET_ONE_INSTITUTION_FAILED';

export const GET_INSTITUTION_POSTS = 'GET_INSTITUTION_POSTS';
export const GET_INSTITUTION_POSTS_SUCCESS = 'GET_INSTITUTION_POSTS_SUCCESS';
export const GET_INSTITUTION_POSTS_FAILED = 'GET_INSTITUTION_POSTS_FAILED';

export const GET_INSTITUTION_TEACHERS_LIST = 'GET_INSTITUTION_TEACHERS_LIST';
export const GET_INSTITUTION_TEACHERS_LIST_SUCCESS = 'GET_INSTITUTION_TEACHERS_LIST_SUCCESS';
export const GET_INSTITUTION_TEACHERS_LIST_FAILED = 'GET_INSTITUTION_TEACHERS_LIST_FAILED';