export const GET_MY_INSTITUTIONS = 'GET_MY_INSTITUTIONS';
export const GET_MY_INSTITUTIONS_SUCCESS = 'GET_MY_INSTITUTIONS_SUCCESS';
export const GET_MY_INSTITUTIONS_FAILED = 'GET_MY_INSTITUTIONS_FAILED';
