export const GET_MY_INSTITUTIONS = 'GET_MY_INSTITUTIONS';
export const GET_MY_INSTITUTIONS_SUCCESS = 'GET_MY_INSTITUTIONS_SUCCESS';
export const GET_MY_INSTITUTIONS_FAILED = 'GET_MY_INSTITUTIONS_FAILED';


export const GET_INSTITUTION_POSTS = 'GET_INSTITUTION_POSTS';
export const GET_INSTITUTION_POSTS_SUCCESS = 'GET_INSTITUTION_POSTS_SUCCESS';
export const GET_INSTITUTION_POSTS_FAILED = 'GET_INSTITUTION_POSTS_FAILED';

