export const GET_INVITATIONS_LIST = 'GET_INVITATIONS_LIST';
export const GET_INVITATIONS_LIST_SUCCESS = 'GET_INVITATIONS_LIST_SUCCESS';
export const GET_INVITATIONS_LIST_FAILED = 'GET_INVITATIONS_LIST_FAILED';
