export const GET_ONE_NETWORK = 'GET_ONE_NETWORK';
export const GET_ONE_NETWORK_SUCCESS = 'GET_ONE_NETWORK_SUCCESS';
export const GET_ONE_NETWORK_FAILED = 'GET_ONE_NETWORK_FAILED';

export const ACCEPT_MEMBER_NETWORK = 'ACCEPT_MEMBER_NETWORK';
export const ACCEPT_MEMBER_NETWORK_SUCCESS = 'ACCEPT_MEMBER_NETWORK_SUCCESS';
export const ACCEPT_MEMBER_NETWORK_FAILED = 'ACCEPT_MEMBER_NETWORK_FAILED';

export const ADD_MEMBER_NETWORK = 'ADD_MEMBER_NETWORK';
export const ADD_MEMBER_NETWORK_SUCCESS = 'ADD_MEMBER_NETWORK_SUCCESS';
export const ADD_MEMBER_NETWORK_FAILED = 'ADD_MEMBER_NETWORK_FAILED';
