export const GET_ONE_NOTIFICATION = 'GET_ONE_NOTIFICATION';
export const GET_ONE_NOTIFICATION_SUCCESS = 'GET_ONE_NOTIFICATION_SUCCESS';
export const GET_ONE_NOTIFICATION_FAILED = 'GET_ONE_NOTIFICATION_FAILED';

export const GET_LIST_NOTIFICATIONS = 'GET_LIST_NOTIFICATIONS';
export const GET_LIST_NOTIFICATIONS_SUCCESS = 'GET_LIST_NOTIFICATIONS_SUCCESS';
export const GET_LIST_NOTIFICATIONS_FAILED = 'GET_LIST_NOTIFICATIONS_FAILED';
