export const GET_MY_PARTNERS = 'GET_MY_PARTNERS';
export const GET_MY_PARTNERS_SUCCESS = 'GET_MY_PARTNERS_SUCCESS';
export const GET_MY_PARTNERS_FAILED = 'GET_MY_PARTNERS_FAILED';

export const GET_PARTNER_POSTS = 'GET_PARTNER_POSTS';
export const GET_PARTNER_POSTS_SUCCESS = 'GET_PARTNER_POSTS_SUCCESS';
export const GET_PARTNER_POSTS_FAILED = 'GET_PARTNER_POSTS_FAILED';

export const GET_ONE_PARTNER = 'GET_ONE_PARTNER';
export const GET_ONE_PARTNER_SUCCESS = 'GET_ONE_PARTNER_SUCCESS';
export const GET_ONE_PARTNER_FAILED = 'GET_ONE_PARTNER_FAILED';

export const EDIT_PARTNER = 'EDIT_PARTNER';
export const EDIT_PARTNER_SUCCESS = 'EDIT_PARTNER_SUCCESS';
export const EDIT_PARTNER_FAILED = 'EDIT_PARTNER_FAILED';

export const GET_LIST_PARTNERS = 'GET_LIST_PARTNERS';
export const GET_LIST_PARTNERS_SUCCESS = 'GET_LIST_PARTNERS_SUCCESS';
export const GET_LIST_PARTNERS_FAILED = 'GET_LIST_PARTNERS_FAILED';
