export const GET_POSTS_LIST = 'GET_POSTS_LIST';
export const GET_POSTS_LIST_SUCCESS = 'GET_POSTS_LIST_SUCCESS';
export const GET_POSTS_LIST_FAILED = 'GET_POSTS_LIST_FAILED';

export const GET_POSTS_COMMENTS_LIST = 'GET_POSTS_COMMENTS_LIST';
export const GET_POSTS_COMMENTS_LIST_SUCCESS = 'GET_POSTS_COMMENTS_LIST_SUCCESS';
export const GET_POSTS_COMMENTS_LIST_FAILED = 'GET_POSTS_COMMENTS_LIST_FAILED';

export const LIKE_POST = 'LIKE_POST';
export const LIKE_POST_SUCCESS = 'LIKE_POST_SUCCESS';
export const LIKE_POST_FAILED = 'LIKE_POST_FAILED';