export const GET_POSTS_LIST = 'GET_POSTS_LIST';
export const GET_POSTS_LIST_SUCCESS = 'GET_POSTS_LIST_SUCCESS';
export const GET_POSTS_LIST_FAILED = 'GET_POSTS_LIST_FAILED';

export const GET_TEACHER_POSTS = 'GET_TEACHER_POSTS';
export const GET_TEACHER_POSTS_SUCCESS = 'GET_TEACHER_POSTS_SUCCESS';
export const GET_TEACHER_POSTS_FAILED = 'GET_POSTS_LIST_FAILED';

export const GET_POSTS_COMMENTS_LIST = 'GET_POSTS_COMMENTS_LIST';
export const GET_POSTS_COMMENTS_LIST_SUCCESS = 'GET_POSTS_COMMENTS_LIST_SUCCESS';
export const GET_POSTS_COMMENTS_LIST_FAILED = 'GET_POSTS_COMMENTS_LIST_FAILED';

export const LIKE_POST = 'LIKE_POST';
export const LIKE_POST_SUCCESS = 'LIKE_POST_SUCCESS';
export const LIKE_POST_FAILED = 'LIKE_POST_FAILED';

export const POST_POST = 'POST_POST';
export const POST_POST_SUCCESS = 'POST_POST_SUCCESS';
export const POST_POST_FAILED = 'POST_POST_FAILED';