export const GET_TEACHERS_LIST = 'GET_TEACHERS_LIST';
export const GET_TEACHERS_LIST_SUCCESS = 'GET_TEACHERS_LIST_SUCCESS';
export const GET_TEACHERS_LIST_FAILED = 'GET_TEACHERS_LIST_FAILED';

export const GET_ONE_TEACHER = 'GET_ONE_TEACHER';
export const GET_ONE_TEACHER_SUCCESS = 'GET_ONE_TEACHER_SUCCESS';
export const GET_ONE_TEACHER_FAILED = 'GET_ONE_TEACHER_FAILED';
