export const GET_TRAININGS_LIST = 'GET_TRAININGS_LIST';
export const GET_TRAININGS_LIST_SUCCESS = 'GET_TRAININGS_LIST_SUCCESS';
export const GET_TRAININGS_LIST_FAILED = 'GET_TRAININGS_LIST_FAILED';


export const CREATE_NEW_TRAINING = 'CREATE_NEW_TRAINING';
export const CREATE_NEW_TRAINING_SUCCESS = 'CREATE_NEW_TRAINING_SUCCESS';
export const CREATE_NEW_TRAINING_FAILED = 'CREATE_NEW_TRAINING_FAILED';
