export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED';

export const EDIT_USER = 'EDIT_USER';
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS';
export const EDIT_USER_FAILED = 'EDIT_USER_FAILED';

export const SELECT_SPACE = 'SELECT_SPACE';
export const SELECT_SPACE_SUCCESS = 'SELECT_SPACE_SUCCESS';
export const SELECT_SPACE_FAILED = 'SELECT_SPACE_FAILED';