export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED';

export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAILED = 'CHANGE_PASSWORD_FAILED';

export const VERIF_PHONE = 'VERIF_PHONE';
export const VERIF_PHONE_SUCCESS = 'VERIF_PHONE_SUCCESS';
export const VERIF_PHONE_FAILED = 'VERIF_PHONE_FAILED';

export const CONFIRM_PHONE_TOKEN = 'CONFIRM_PHONE_TOKEN';
export const CONFIRM_PHONE_TOKEN_SUCCESS = 'CONFIRM_PHONE_TOKEN_SUCCESS';
export const CONFIRM_PHONE_TOKEN_FAILED = 'CONFIRM_PHONE_TOKEN_FAILED';

export const VERIF_EMAIL = 'VERIF_EMAIL';
export const VERIF_EMAIL_SUCCESS = 'VERIF_EMAIL_SUCCESS';
export const VERIF_EMAIL_FAILED = 'VERIF_EMAIL_FAILED';

export const CONFIRM_EMAIL_TOKEN = 'CONFIRM_EMAIL_TOKEN';
export const CONFIRM_EMAIL_TOKEN_SUCCESS = 'CONFIRM_EMAIL_TOKEN_SUCCESS';
export const CONFIRM_EMAIL_TOKEN_FAILED = 'CONFIRM_EMAIL_TOKEN_FAILED';

export const GET_PROFILE_USER = 'GET_PROFILE_USER';
export const GET_PROFILE_USER_SUCCESS = 'GET_PROFILE_USER_SUCCESS';
export const GET_PROFILE_USER_FAILED = 'GET_PROFILE_USER_FAILED';

export const EDIT_USER = 'EDIT_USER';
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS';
export const EDIT_USER_FAILED = 'EDIT_USER_FAILED';

export const SELECT_SPACE = 'SELECT_SPACE';
export const SELECT_SPACE_SUCCESS = 'SELECT_SPACE_SUCCESS';
export const SELECT_SPACE_FAILED = 'SELECT_SPACE_FAILED';

export const LOGOUT = 'LOGOUT';
