export const trainingThemes = [
  {
    label: 'Achat, Logistique',
    desc: 'Stock , import-export',
    value: 'Achat-Logistique',
    key: 0,
  },
  {
    label: 'Animaux, Nature',
    desc: 'Agriculture, soins vétérinaire, Fleuriste',
    value: 'Animaux-Nature',
    key: 1,
  },
  {
    label: 'Art, Design, Décoration',
    desc: 'Déco, Photographie, Couture, Gaphisme',
    value: 'Art-Design-Décoration',
    key: 2,
  },
  {
    label: 'Artisanat, Petit Commerce',
    desc: 'Menuiserie, Plomberie, Serrurerie, Services',
    value: 'Artisanat-PetitCommerce',
    key: 3,
  },
  {
    label: 'Banque , Finanace, Assurance',
    desc: 'Banque, Assurance, Trading',
    value: 'Banque-Finanace-Assurance',
    key: 4,
  },
  {
    label: 'Bien-Etre, Relaxation',
    desc: 'Naturopathie, Sophrolgie, Massage, Hypnose',
    value: 'Bien-Etre-Relaxation',
    key: 5,
  },
  {
    label: 'Bilan De Compétance, VAE',
    desc: 'Orientation, Bilan professionnel',
    value: 'Bilan-De-Compétance-VAE',
    key: 6,
  },
  {
    label: 'BTP, Travaux, Architecture',
    desc: 'Conduite de travaux, Electricité, Autocad',
    value: 'BTP-Travaux-Architecture',
    key: 7,
  },
  {
    label: 'Bureautique, Office',
    desc: 'Excel, Word , Google Docs',
    value: 'Bureautique',
    key: 8,
  },
  {
    label: 'Commerce, Marketing',
    desc: 'Vente, Relation Client',
    value: 'Commerce',
    key: 9,
  },
  {
    label: 'Communication, Evénementiel',
    desc: 'wedding planner, Evénement, Journalisme',
    value: 'Communication',
    key: 10,
  },
  {
    label: 'Comptabilité, Gestion',
    desc: 'Comptabilité, Gestion',
    value: 'Comptabilité',
    key: 11,
  },
  {
    label: 'Défense, Sécurité, Secourisme',
    desc: 'Agent de sécurité, incendie, SST, Gendarmie',
    value: 'Défense-Sécurité-Secourisme',
    key: 12,
  },
  {
    label: 'Développement Personnel, Epanouissement',
    desc: 'Gestion du stress, PNL, Prise de parole',
    value: 'Développement-Personnel',
    key: 13,
  },
  {
    label: 'Digital, Internet',
    desc: 'Web design, Community management, SEO, SEA',
    value: 'Digital',
    key: 14,
  },
  {
    label: 'Enseignement, Coaching',
    desc: 'Formateur, coach sportif, coach de vie',
    value: 'Enseignement',
    key: 15,
  },
  {
    label: 'Esthétique, Coiffure',
    desc: 'Prothésiste Ongulaire, Maquillage, Manucure',
    value: 'Esthétique',
    key: 16,
  },
  {
    label: 'Fonction Publique, Citoyenneté, Droit',
    desc: 'Politique, RGPD, Juridique',
    value: 'Fonction-Publique-Droit',
    key: 17,
  },
  {
    label: 'Hotellerie, Restauration, Cuisine',
    desc: 'Patisserie, Barman, Diétitique, Bulanger',
    value: 'Hotellerie',
    key: 18,
  },
  {
    label: 'Immobilier, Urbanisme',
    desc: 'Agent Immobilier, Gestion Locative',
    value: 'Immobilier',
    key: 19,
  },
  {
    label: 'Industrie, Matériaux, Energie',
    desc: 'Mécanique, soudure, Agroalimentaire, Electronique',
    value: 'Industrie',
    key: 20,
  },
  {
    label: 'Informatique, DATA, SIG',
    desc: 'Développeur Web, data, cybersécurity',
    value: 'Informatique',
    key: 21,
  },
  {label: 'Langues', desc: 'Anglais, Français, ...', value: 'Langues', key: 22},
  {label: 'Autre', desc: '', value: 'autre', key: 100},
];
